#!/usr/bin/env sh
# Script to start dwm in loop

while true; do
		$HOME/suckless/scripts/dwm-status.sh
    	sleep 3
done &

while true; do
	dwm >/dev/null
	# to log stderrors to a file
	# dwm 2> ~/Build/dwm/dwm.log
done
