#!/usr/bin/env zsh
# Status script for dwm

# The MIT License (MIT) http://opensource.org/licenses/MIT


music(){
  track="$(mpc current)"
  artist="${track%%- *}"
  title="${track#*- }"
  [[ -n $artist ]] && printf "%b" "• $artist - $title "
}

vol(){
  vol="$(pactl list sinks | grep 'Volume' |awk 'FNR == 1 {print $5}')"
  printf "%b" "$vol"
}

bat(){
  onl="$(</sys/class/power_supply/AC/online)"
  charge0="$(</sys/class/power_supply/BAT0/capacity)"
  charge1="$(</sys/class/power_supply/BAT1/capacity)"
  if [[ $onl -eq 0 && $charge0 -ge 15 ]] || [[ $onl -eq 0 && $charge1 -ge 15 ]]; then
    printf "BAT $charge0 $charge1 "
  elif [[ $onl -eq 0 && $charge0 -le 14 ]] || [[ $onl -eq 0 && $charge1 -le 14 ]]; then
    printf "BAT $charge0 $charge1 "
  else
    printf "AC $charge0 $charge1 "
  fi
}

mem(){
  mem="$(awk '/^Mem/ {print $3}' <(free -m))"
  printf "%b" "$mem"
}

cpu(){
  ~/src/scripts/cpu.py
}

hdd(){
  ~/src/scripts/hdd.py
}

eml(){
  maildirs="imaps://imap.gmail.com:993"
  ml="$(find $maildirs -type f | wc -l)"
  if (( ml > 0 )); then
    printf "%b" "\x03$ml\x01"
  else
    printf "0"
  fi
}

dte(){
  dte="$(date "+%T_%m-%d")"
  printf "%b" "$dte"
}

kb(){
  keys="$(xkblayout-state print "%s")"
  printf "%b" "$keys"
}

# Pipe to status bar
#xsetroot -name "$(music) • CPU $(cpu) • MEM $(mem) • HDD $(hdd)\
#• NET $(int) • $(dte) • VOL $(vol) "
xsetroot -name "$(music) • cpu $(cpu)% • $(bat)• $(hdd) • $(dte) • vol $(vol) • $(kb)"